# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # Configure NuGet sources including GitHub Packages
    - name: Configure NuGet Sources
      run: |
        dotnet nuget add source "https://api.nuget.org/v3/index.json" -n nuget.org
        dotnet nuget add source "https://nuget.pkg.github.com/YOUR_GITHUB_USERNAME/index.json" -n github
      
    # Add GitHub Packages authentication
    - name: Authenticate GitHub Packages
      run: |
        dotnet nuget update source github \
          --username YOUR_GITHUB_USERNAME \
          --password ${{ secrets.GITHUB_PACKAGE_TOKEN }} \
          --store-password-in-clear-text

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
