# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Authenticate to GitHub Packages
      run: echo "//nuget.pkg.github.com/andrei-shershan/index.json" > ~/.nuget/NuGet/NuGet.Config
      env:
        GITHUB_TOKEN: ${{ secrets.kinodev-shared-token-read }}
    - name: Restore dependencies
      run: dotnet restore --source https://nuget.pkg.github.com/andrei-shershan/index.json
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
